### ISSUE TITLE
Another redump parsing issue

### ISSUE THREAD

**Issue by alucryd** [SnowflakePowered/shiratsu#11]
Hi there, a new dreamcast entry is erroring out:
```
{ err: "Failed to parse no-intro name, The name \"Neo XYX (Europe) (Unl))\" could not be parsed properly in the NoIntro naming convention" }
```
Could you have a look?

**Comment by chyyran** [comment]
I’m on vacation right now but I’ll take a look once I get back.

**Comment by alucryd** [comment]
Thanks for the quick reply. Take your time and enjoy your vacation!

**Comment by chyyran** [comment]
This isn't a problem with the parser, the name itself is invalid.

`Neo XYX (Europe) (Unl))` has an extra `)` that fails validation. `Neo XYX (Europe) (Unl)` parses fine as `[Title("Neo XYX"), Region(["Europe"], [Europe]), Flag(Parenthesized, "Unl")`.

Looking at the [redump entry](http://redump.org/disc/95803/) for this, `Neo XYX (Europe) (Unl)` should be the correct name following the convention used.

**Comment by alucryd** [comment]
Oh, indeed! Sorry about the noise.
