### ISSUE TITLE
Upgrade nom to v7

### ISSUE THREAD

**Issue by alucryd** [SnowflakePowered/shiratsu#8]
Hi there, would it be possible to upgrade nom to the latest version? v6 is causing issues with tarpaulin and recent rust versions, see https://github.com/xd009642/tarpaulin/issues/756

Thanks in advance.

**Comment by xd009642** [comment]
Just FYI I just checked and it nom can be changed from 6 to 7 without any code changes (breaking change was removing the nom macros which shiratsu doesn't use). 

Also a github merge conflict was committed into the Cargo.lock in 75dd8b7). I've fixed it in the local version I pulled and don't mind doing a PR but it's also a small change and I see there aren't any other contributors so don't know if you're accepting PRs?

**Comment by chyyran** [comment]
Thanks for updating this for me. I don't have CI set up so let me make sure all the tests past locally and I'll go ahead and merge this.

**Comment by chyyran** [comment]
Also sorry for not replying earlier. My Github notifications have been a bit messed up so I'll have to get that fixed later.

**Comment by chyyran** [comment]
Published https://crates.io/crates/shiratsu-naming/0.1.4

Thanks @alucryd @xd009642
